#!/usr/bin/env python3
# -*- coding:utf-8 -*-
import os
import codecs
import time

from common import *

MENU_LIST = './menuList.txt'
USER_PATH = './user'
MENU_PATH = './menu'
GEN_PATH = './'


class OriginGen:
    """
    osd origin  generator
    """

    def __init__(self, inFile, outPath):
        self.inFile = inFile
        self.outPath = outPath

    def gen_user_c(self):
        OUT_PATH = self.outPath
        IN_FILE = self.inFile
        fin = codecs.open(IN_FILE, encoding='utf-8', mode='r')
        if not os.path.exists(OUT_PATH):
            os.makedirs(OUT_PATH)
        OUT_FILE =  OUT_PATH + '/'+ 'user_menu.c'
        init_model = "menu<MUNENAME>_initialize();\n"
        menu_user_c_str = "\
/**\n\
 * File      : user_menu.c\n\
 * This file is automatically generated by OriginGen.py\n\
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY\n\
 *\n\
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.\n\
 * All rights reserved\n\
 *\n\
 * Generated at: <DATE>\n\
 */\n\
\n\
#include \"menu/menu_list.h\"\n\
\n\
void initializeUserMenu() {\n"
        for line in fin:
            init_string = init_model.replace('<MUNENAME>',camel_case(line.strip()))
            menu_user_c_str +='    ' +init_string
        fin.close()
        menu_user_c_str += '};\n'
        menu_user_c_str = menu_user_c_str.replace('<DATE>', time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
        FOUT = codecs.open(OUT_FILE, encoding='utf-8', mode='w')
        FOUT.write(menu_user_c_str)
        FOUT.close()

    def gen_user_h(self):
        OUT_PATH = self.outPath
        IN_FILE = self.inFile
        fin = codecs.open(IN_FILE, encoding='utf-8', mode='r')
        if not os.path.exists(OUT_PATH):
            os.makedirs(OUT_PATH)
        OUT_FILE =  OUT_PATH + '/'+ 'user_menu.h'
        init_model = "    MENU_<MENUNAMEUP>,\n"
        menu_user_h_str = "\
/**\n\
 * File      : user_menu.h\n\
 * This file is automatically generated by OriginGen.py\n\
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY\n\
 *\n\
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.\n\
 * All rights reserved\n\
 *\n\
 * Generated at:<DATE>\n\
 */\n\
\n\
#ifndef _USER_MENU_H_\n\
#define _USER_MENU_H_\n\
\n\
#define MENU_NUM <NUM>\n\
enum {\n"
        num = 0
        for line in fin:
            num = num +1
            init_string = init_model.replace('<MENUNAMEUP>',line.strip().upper())
            menu_user_h_str += init_string
        fin.close()
        menu_user_h_str = menu_user_h_str.replace('<NUM>',str(num))\
         .replace('<DATE>', time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
        menu_user_h_str +='};\n\nvoid initializeUserMenu();\n\n#endif'
        FOUT = codecs.open(OUT_FILE, encoding='utf-8', mode='w')
        FOUT.write(menu_user_h_str)
        FOUT.close()

    def gen_str_index(self):
        OUT_PATH = self.outPath
        IN_FILE = self.inFile
        fin = codecs.open(IN_FILE, encoding='utf-8', mode='r')
        if not os.path.exists(OUT_PATH):
            os.makedirs(OUT_PATH)
        OUT_FILE =  OUT_PATH + '/'+ 'user_str_index.c'
        init_model = "str_<MENUNAME>[0]"
        str_index_string =  "\n\
char *osd_string_index[MENU_NUM] = {\n\
"
        for line in fin:
            init_string = "    "
            init_string += init_model.replace('<MENUNAME>',line.strip())
            init_string += ',\n'
            str_index_string += init_string
        fin.close()
        str_index_string = str_index_string
        str_index_string += '};'
        FOUT = codecs.open(OUT_FILE, encoding='utf-8', mode='w')
        FOUT.write(str_index_string)
        FOUT.close()

    def gen_user_string_h(self):
        OUT_PATH = self.outPath
        if not os.path.exists(OUT_PATH):
            os.makedirs(OUT_PATH)
        OUT_FILE =  OUT_PATH + '/'+ 'user_string.h'
        str_user_string =  '#ifndef _USER_STRING_H_\n\
#define _USER_STRING_H_\n\
#include "user_menu.h"\n\n\
#define MAX_STR_LEN 32\n\
#define MAX_COMPONENT_PER_NUM 32\n\
\n\
extern char *osd_string_index[MENU_NUM];\n\
\n\
#endif\n\
'
        FOUT = codecs.open(OUT_FILE, encoding='utf-8', mode='w')
        FOUT.write(str_user_string)
        FOUT.close()

    def gen_user_string_c(self):
        OUT_PATH = self.outPath
        if not os.path.exists(OUT_PATH):
            os.makedirs(OUT_PATH)
        OUT_FILE =  OUT_PATH + '/'+ 'user_string.c'
        str_user_string =  ' /* File      : user_string.c\n\
 * This file is automatically generated by OriginGen.py & OsdStringGenIPC.py\n\
 *\n\
 * Copyright (c) 2023 Shanghai Fullhan Microelectronics Co., Ltd.\n\
 * All rights reserved\n\
 *\n\
 * Generated at:<DATE>\n\
 */\n\
#include "user_string.h"\n\
#include "user_menu.h"\n\n\
'
        FOUT = codecs.open(OUT_FILE, encoding='utf-8', mode='w')
        str_user_string = str_user_string.replace('<DATE>', time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
        FOUT.write(str_user_string)
        FOUT.close()

    def gen_list_h(self):
        OUT_PATH = self.outPath
        IN_FILE = self.inFile
        fin = codecs.open(IN_FILE, encoding='utf-8', mode='r')
        if not os.path.exists(OUT_PATH):
            os.makedirs(OUT_PATH)
        OUT_FILE =  OUT_PATH + '/'+ 'menu_list.h'
        init_model = "#include \"menu_<MENUNAME>.h\"\n"
        menu_list_h_str = "\
/**\n\
 * File      : menu_list.h\n\
 * This file is automatically generated by OriginGen.py\n\
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY\n\
 *\n\
 * Copyright (c) 2016 Shanghai Fullhan Microelectronics Co., Ltd.\n\
 * All rights reserved\n\
 *\n\
 * Script Version: 1.0\n\
 * Generated at:<DATE>\n\
 */\n\
\n\
#ifndef _MEUN_LIST_H_\n\
#define _MEUN_LIST_H_\n\
\n"
        for line in fin:
            init_string = init_model.replace('<MENUNAME>',line.strip())
            menu_list_h_str += init_string
        fin.close()
        menu_list_h_str = menu_list_h_str.replace('<DATE>', time.strftime("%Y-%m-%d %H:%M:%S", time.localtime()))
        menu_list_h_str +='#endif // !_MEUN_LIST_H_\n'
        FOUT = codecs.open(OUT_FILE, encoding='utf-8', mode='w')
        FOUT.write(menu_list_h_str)
        FOUT.close()


    def gen_gencode(self):
        OUT_PATH = self.outPath
        IN_FILE = self.inFile
        fin = codecs.open(IN_FILE, encoding='utf-8', mode='r')
        if not os.path.exists(OUT_PATH):
            os.makedirs(OUT_PATH)
        OUT_FILE =  OUT_PATH + '/'+ 'gencode.sh'
        init_model = "python3 menu_create.py ./in/<MENUNAME>.ini ./menu ./callback\n"
        gencode_str =  "\
# gen code\n\
# menu_create.py <input_ini> <output folder>\n\
\n"
        for line in fin:
            init_string = init_model.replace('<MENUNAME>',line.strip())
            gencode_str += init_string
        fin.close()
        gencode_str += 'cp ./configure.c ./menu/configure.c\n\
cp ./configure.h ./menu/configure.h\n\
'
        FOUT = codecs.open(OUT_FILE, encoding='utf-8', mode='w')
        FOUT.write(gencode_str)
        FOUT.close()

    def gen_genstring(self):
        OUT_PATH = self.outPath
        IN_FILE = self.inFile
        fin = codecs.open(IN_FILE, encoding='utf-8', mode='r')
        if not os.path.exists(OUT_PATH):
            os.makedirs(OUT_PATH)
        OUT_FILE =  OUT_PATH + '/'+ 'genstring.sh'
        init_model = "python3 OsdStringGenIPC.py ./in/<MENUNAME>.ini\n"
        genstr_str =  "\
# extract string from ini file\n\
# OsdStringGenIPC.py <input_ini> \n\
\n"
        for line in fin:
            init_string = init_model.replace('<MENUNAME>',line.strip())
            genstr_str += init_string
        fin.close()
        FOUT = codecs.open(OUT_FILE, encoding='utf-8', mode='w')
        FOUT.write(genstr_str)
        FOUT.close()

if __name__ == '__main__':


    OGU = OriginGen(MENU_LIST,USER_PATH)
    OGM = OriginGen(MENU_LIST,MENU_PATH)
    OGG = OriginGen(MENU_LIST,GEN_PATH)
    OGU.gen_user_c()
    OGU.gen_user_h()
    OGU.gen_str_index()
    OGU.gen_user_string_h()
    OGU.gen_user_string_c()
    OGM.gen_list_h()
    OGG.gen_gencode()
    OGG.gen_genstring()
    exit()

