/**
 * Copyright (c) 2015-2019 Shanghai Fullhan Microelectronics Co., Ltd.
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 *
 * Change Logs:
 * Date           Author       Notes
 * 2019-01-24     tangyh    the first version
 *
 */

#ifndef __CLOCK_CONFIG_H__
#define __CLOCK_CONFIG_H__

#include <rtdef.h>
#include "fh_clock.h"
#include "fh_pmu.h"

#define OSC_FREQUENCY  24000000   /*24M hz*/

#define RT_UINT9_MAX                    0x1ff
#define RT_UINT8_MAX                    0xff
#define RT_UINT7_MAX                    0x7f
#define RT_UINT6_MAX                    0x3f
#define RT_UINT5_MAX                    0x1f
#define RT_UINT4_MAX                    0xf
#define RT_UINT3_MAX                    0x7
#define RT_UINT2_MAX                    0x3
#define RT_UINT1_MAX                    0x1

static struct clk  fh_clk_list[] = {
    {
        .name               = "osc_clk",
        .flag               = CLOCK_FIXED,
        .clk_out_rate       = 24000000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll0_pclk",
        .flag               = CLOCK_PLL_P,
        .clk_div.reg_offset = REG_DDR_PLL0_CTRL0,
        .clk_gate.reg_offset = REG_DDR_PLL0_CTRL1,
        .clk_gate.mask      = 0xf00,
        .mult_parent        = {"osc_clk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll0_rclk",
        .flag               = CLOCK_PLL_R,
        .clk_div.reg_offset = REG_DDR_PLL0_CTRL0,
        .clk_gate.reg_offset = REG_DDR_PLL0_CTRL1,
        .clk_gate.mask      = 0xf000,
        .mult_parent        = {"osc_clk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll0_r_gate",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_PRE_DIV_GATE,
        .clk_gate.mask      = 0x1,
        .mult_parent        = {"osc_clk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_pclk",
        .flag               = CLOCK_PLL,
        .clk_div.reg_offset = REG_PMU_PLL1_CTRL,
        .mult_parent        = {"osc_clk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll2_pclk",
        .flag               = CLOCK_PLL,
        .clk_div.reg_offset = REG_PMU_PLL2_CTRL,
        .mult_parent        = {"osc_clk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll2_p_gate",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_PRE_DIV_GATE,
        .clk_gate.mask      = 0x4,
        .mult_parent        = {"pll2_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_p_div2",
        .flag               = PREDIV,
        .pre_div            = 2,
        .mult_parent        = {"pll1_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_p_div2_gate",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_PRE_DIV_GATE,
        .clk_gate.mask      = 0x2,
        .mult_parent        = {"osc_clk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_p_div12",
        .flag               = PREDIV,
        .pre_div            = 12,
        .mult_parent        = {"pll1_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_p_div18",
        .flag               = PREDIV,
        .pre_div            = 18,
        .mult_parent        = {"pll1_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_p_div24",
        .flag               = PREDIV,
        .pre_div            = 24,
        .mult_parent        = {"pll1_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_p_div36",
        .flag               = PREDIV,
        .pre_div            = 36,
        .mult_parent        = {"pll1_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_p_div4",
        .flag               = PREDIV,
        .pre_div            = 4,
        .mult_parent        = {"pll1_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_p_div6",
        .flag               = PREDIV,
        .pre_div            = 6,
        .mult_parent        = {"pll1_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_p_div72",
        .flag               = PREDIV,
        .pre_div            = 72,
        .mult_parent        = {"pll1_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll1_p_div9",
        .flag               = PREDIV,
        .pre_div            = 9,
        .mult_parent        = {"pll1_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll2_p_div2",
        .flag               = PREDIV,
        .pre_div            = 2,
        .mult_parent        = {"pll2_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll2_p_div3",
        .flag               = PREDIV,
        .pre_div            = 3,
        .mult_parent        = {"pll2_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pll2_p_div437",
        .flag               = PREDIV,
        .pre_div            = 437,
        .mult_parent        = {"pll2_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "ddr_clk",
        .flag               = PREDIV,
        .pre_div            = 1,
        .mult_parent        = {"pll0_pclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "DA_CLK",
        .flag               = MUX | DIV | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL3,
        .clk_mux.mask       = 0x1000000,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x40000000,
        .clk_div.reg_offset = REG_PMU_CLK_DIV8,
        .clk_div.mask       = 0xff000000,
        .mult_parent        = {"osc_clk", "div_frac_clk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "div_frac_clk",
        .flag               = CLOCK_FIXED,
        .clk_out_rate       = 12288000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "ac_mclk",
        .flag               = MUX | DIV | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL3,
        .clk_mux.mask       = 0x1000000,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x10,
        .clk_div.reg_offset = REG_PMU_CLK_DIV7,
        .clk_div.mask       = 0x3f0000,
        .mult_parent        = {"osc_clk", "div_frac_clk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "acodec_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x200,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "acw_pre_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x40000000,
        .mult_parent        = {"pll1_p_div2"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "arc_clk_core",
        .flag               = MUX,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL0,
        .clk_mux.mask       = 0x30,
        .mult_parent        = {"pll1_p_div4", "pll1_p_div6", "pll2_p_div3", "pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "cpu_clk",
        .flag               = MUX,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL0,
        .clk_mux.mask       = 0x7,
        .mult_parent        = {"osc_clk", "pll2_pclk", "pll0_rclk", "pll1_p_div4", "pll1_p_div6"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "efuse_clk",
        .flag               = DIV | GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x1000000,
        .clk_div.reg_offset = REG_PMU_CLK_DIV1,
        .clk_div.mask       = 0x3f0000,
        .mult_parent        = {"pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "efuse_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x800000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "emac_hclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x1000000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "ephy_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x8,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "ephy_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x400,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "gpio1_dbclk",
        .flag               = MUX | DIV | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL6,
        .clk_mux.mask       = 0x1000,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x10000000,
        .clk_div.reg_offset = REG_PMU_CLK_DIV5,
        .clk_div.mask       = 0x3fff,
        .mult_parent        = {"osc_clk", "pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "gpio1_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x4000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "hclk_core",
        .flag               = MUX,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL0,
        .clk_mux.mask       = 0x3000,
        .mult_parent        = {"osc_clk", "pll1_p_div12", "pll1_p_div18", "pll1_p_div24"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "I2C1_clk",
        .flag               = MUX | DIV | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL5,
        .clk_mux.mask       = 0x10,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x1000,
        .clk_div.reg_offset = REG_PMU_CLK_DIV0,
        .clk_div.mask       = 0x3f00,
        .mult_parent        = {"osc_clk", "pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "i2c1_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x2,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "i2c_clk_core",
        .flag               = MUX | DIV,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL5,
        .clk_mux.mask       = 0x1,
        .clk_div.reg_offset = REG_PMU_CLK_DIV0,
        .clk_div.mask       = 0x3f,
        .mult_parent        = {"osc_clk", "pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "i2s_sclk",
        .flag               = MUX | DIV,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL3,
        .clk_mux.mask       = 0x1000000,
        .clk_div.reg_offset = REG_PMU_CLK_DIV6,
        .clk_div.mask       = 0xff000000,
        .mult_parent        = {"osc_clk", "div_frac_clk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "i2s_ws",
        .flag               = DIV,
        .clk_div.reg_offset = REG_PMU_CLK_DIV6,
        .clk_div.mask       = 0xff,
        .mult_parent        = {"i2s_sclk"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "isp_clk",
        .flag               = MUX | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL1,
        .clk_mux.mask       = 0x7,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x2,
        .mult_parent        = {"pll1_p_div9", "pll1_p_div12", "pll1_p_div18", "pll1_p_div24", "pll1_p_div36"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "isp_hclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x10000,
        .mult_parent        = {"hclk_core"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "jpg_clk",
        .flag               = MUX | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL1,
        .clk_mux.mask       = 0x30,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x40,
        .mult_parent        = {"pll1_p_div9", "pll1_p_div12", "pll1_p_div18", "pll1_p_div24"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "jpg_hclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x80,
        .mult_parent        = {"hclk_core"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "jpg_lb_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x100,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "mipi0_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x400000,
        .mult_parent        = {"hclk_core"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "mipi1_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x800000,
        .mult_parent        = {"hclk_core"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "mipi_cfg_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x20,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "mipi_dphy_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x40000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "mipi_top_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x4,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "mipi_top_hclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x20000,
        .mult_parent        = {"hclk_core"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "nn_clk",
        .flag               = MUX | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL2,
        .clk_mux.mask       = 0x3,
        .clk_gate.reg_offset = REG_PMU_VEU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x100,
        .mult_parent        = {"pll1_p_div4", "pll2_p_div2", "pll1_p_div6", "pll2_p_div3"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "pwm_clk_core",
        .flag               = DIV,
        .clk_div.reg_offset = REG_PMU_CLK_DIV1,
        .clk_div.mask       = 0xff00,
        .mult_parent        = {"pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "sadc_clk",
        .flag               = DIV | GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x4000000,
        .clk_div.reg_offset = REG_PMU_CLK_DIV4,
        .clk_div.mask       = 0x1ff,
        .mult_parent        = {"pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "sadc_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x1000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "sdc0_clk2x",
        .flag               = PREDIV | MUX | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL3,
        .clk_mux.mask       = 0x30000,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x1,
        .pre_div            = 4,
        .mult_parent        = {"pll1_p_div9", "pll1_p_div18", "pll2_p_div437"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "sdc0_clk_drv",
        .flag               = PHASE,
        .clk_div.reg_offset = REG_PMU_CLK_SEL3,
        .clk_div.mask       = 0x7,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "sdc0_clk_sample",
        .flag               = PHASE,
        .clk_div.reg_offset = REG_PMU_CLK_SEL3,
        .clk_div.mask       = 0x70,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "sdc0_hclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x8000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "sdc1_clk2x",
        .flag               = PREDIV | MUX | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL3,
        .clk_mux.mask       = 0x300000,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x2,
        .pre_div            = 4,
        .mult_parent        = {"pll1_p_div9", "pll1_p_div18", "pll2_p_div437"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "sdc1_clk_drv",
        .flag               = PHASE,
        .clk_div.reg_offset = REG_PMU_CLK_SEL3,
        .clk_div.mask       = 0x700,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "sdc1_clk_sample",
        .flag               = PHASE,
        .clk_div.reg_offset = REG_PMU_CLK_SEL3,
        .clk_div.mask       = 0x7000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "sdc1_hclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x10000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "spi1_clk",
        .flag               = MUX | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL4,
        .clk_mux.mask       = 0x30,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x200,
        .mult_parent        = {"pll1_p_div18", "pll1_p_div24", "pll1_p_div36", "pll1_p_div72"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "spi1_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x40000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "spi0_clk",
        .flag               = MUX | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL4,
        .clk_mux.mask       = 0x3,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x100,
        .mult_parent        = {"pll1_p_div9", "pll1_p_div12", "pll1_p_div18", "pll1_p_div36"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "spi0_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x20000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "stm_clk",
        .flag               = DIV | GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x4,
        .clk_div.reg_offset = REG_PMU_CLK_DIV0,
        .clk_div.mask       = 0x3f0000,
        .mult_parent        = {"pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "stm_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x4,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "timer_clk_core",
        .flag               = DIV,
        .clk_div.reg_offset = REG_PMU_CLK_DIV7,
        .clk_div.mask       = 0xff,
        .mult_parent        = {"pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "tmr1_clk",
        .flag               = DIV | GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x80000000,
        .clk_div.reg_offset = REG_PMU_CLK_DIV7,
        .clk_div.mask       = 0xff00,
        .mult_parent        = {"pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "tmr1_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE1,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x800,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "uart1_clk",
        .flag               = MUX | DIV | GATE,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL5,
        .clk_mux.mask       = 0x1000000,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x40000,
        .clk_div.reg_offset = REG_PMU_CLK_DIV2,
        .clk_div.mask       = 0x3f00,
        .mult_parent        = {"osc_clk", "pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "uart1_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x40,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "uart_clk_core",
        .flag               = MUX | DIV,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL5,
        .clk_mux.mask       = 0x100000,
        .clk_div.reg_offset = REG_PMU_CLK_DIV2,
        .clk_div.mask       = 0x3f,
        .mult_parent        = {"osc_clk", "pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "usb_hclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x800000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "veu_clk",
        .flag               = MUX | GATE,
        .clk_gate.reg_offset = REG_PMU_VEU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x1,
        .clk_mux.reg_offset = REG_PMU_CLK_SEL1,
        .clk_mux.mask       = 0x300,
        .mult_parent        = {"pll1_p_div4", "pll2_p_div2", "pll2_p_div3", "pll1_p_div18"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "vpu_hclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x80000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "vpu_lb_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_ISP_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x20,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "wdt_clk",
        .flag               = DIV,
        .clk_div.reg_offset = REG_PMU_CLK_DIV5,
        .clk_div.mask       = 0xff0000,
        .mult_parent        = {"hclk_core"},
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "wdt_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CLK_GATE2,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x8,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "dmac0_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CPU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x4,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "arm11_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CPU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x8,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "intc_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CPU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x10,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "aes_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_CPU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x20,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "veu_lb_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_VEU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x4,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "veu_sysmem_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_VEU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x8,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "nn_sysmem_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_VEU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x200,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "veu_hclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_VEU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x10000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "nn_hclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_VEU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x20000,
        .clk_config         = UNCONFIG,
    },
    {
        .name               = "ahb_sysmem_clk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_PMU_VEU_GATE,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x40000,
        .clk_config         = UNCONFIG,
    },
        {
        .name               = "rc_clk_src",
        .flag               = CLOCK_FIXED,
        .clk_out_rate       = 100000000,
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "arc_clk",
        .flag               = MUX | GATE,
        .clk_mux.reg_offset = REG_AON_CLK_SEL0,
        .clk_mux.mask       = 0x10,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x1,
        .mult_parent        = {"arc_clk_temp", "arc_clk_core"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
        .aon_temp_type      = 1,
    },
    {
        .name               = "ahb_clk",
        .flag               = MUX,
        .clk_mux.reg_offset = REG_AON_CLK_SEL0,
        .clk_mux.mask       = 0x1000,
        .mult_parent        = {"hclk_temp", "hclk_core"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
        .aon_temp_type      = 1,
    },
    {
        .name               = "I2C0_clk",
        .flag               = MUX | GATE,
        .clk_mux.reg_offset = REG_AON_CLK_SEL1,
        .clk_mux.mask       = 0x1000000,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x10000,
        .mult_parent        = {"i2c_clk_temp", "i2c_clk_core"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
        .aon_temp_type      = 1,
    },
    {
        .name               = "pwm_clk",
        .flag               = MUX | GATE,
        .clk_mux.reg_offset = REG_AON_CLK_SEL1,
        .clk_mux.mask       = 0x10000,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x4000,
        .mult_parent        = {"pwm_clk_temp", "pwm_clk_core"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
        .aon_temp_type      = 1,
    },
    {
        .name               = "tmr0_clk",
        .flag               = MUX | GATE,
        .clk_mux.reg_offset = REG_AON_CLK_SEL0,
        .clk_mux.mask       = 0x10000000,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x8,
        .mult_parent        = {"timer_clk_temp", "timer_clk_core"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
        .aon_temp_type      = 1,
    },
    {
        .name               = "uart0_clk",
        .flag               = MUX | GATE,
        .clk_mux.reg_offset = REG_AON_CLK_SEL0,
        .clk_mux.mask       = 0x100000,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x4,
        .mult_parent        = {"uart_clk_temp", "uart_clk_core"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
        .aon_temp_type      = 1,
    },
    {
        .name               = "arc_clk_temp",
        .flag               = MUX | DIV,
        .clk_mux.reg_offset = REG_AON_CLK_SEL0,
        .clk_mux.mask       = 0x1,
        .clk_div.reg_offset = REG_AON_CLK_DIV0,
        .clk_div.mask       = 0xff,
        .mult_parent        = {"osc_clk", "rc_clk_src"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "cis0_clk",
        .flag               = MUX | GATE | DIV,
        .clk_mux.reg_offset = REG_AON_CLK_SEL1,
        .clk_mux.mask       = 0x100,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x2000,
        .clk_div.reg_offset = REG_AON_CLK_DIV2,
        .clk_div.mask       = 0xff,
        .mult_parent        = {"osc_clk", "rc_clk_src"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "gpio_dbclk",
        .flag               = MUX | DIV | GATE,
        .clk_mux.reg_offset = REG_AON_CLK_SEL1,
        .clk_mux.mask       = 0x1,
        .clk_div.reg_offset = REG_AON_CLK_DIV1,
        .clk_div.mask       = 0xff,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x10,
        .mult_parent        = {"osc_clk", "rc_clk_src"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "gpio_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x100,
        .mult_parent        = {"ahb_clk"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "hclk_temp",
        .flag               = MUX | DIV,
        .clk_mux.reg_offset = REG_AON_CLK_SEL0,
        .clk_mux.mask       = 0x100,
        .clk_div.reg_offset = REG_AON_CLK_DIV0,
        .clk_div.mask       = 0xff00,
        .mult_parent        = {"osc_clk", "rc_clk_src"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "i2c_clk_temp",
        .flag               = MUX | DIV,
        .clk_mux.reg_offset = REG_AON_CLK_SEL1,
        .clk_mux.mask       = 0x100000,
        .clk_div.reg_offset = REG_AON_CLK_DIV2,
        .clk_div.mask       = 0xff0000,
        .mult_parent        = {"osc_clk", "rc_clk_src"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "i2c_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x80000,
        .mult_parent        = {"ahb_clk"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "pts_clk",
        .flag               = MUX | DIV | GATE,
        .clk_mux.reg_offset = REG_AON_CLK_SEL1,
        .clk_mux.mask       = 0x10,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x1000,
        .clk_div.reg_offset = REG_AON_CLK_DIV1,
        .clk_div.mask       = 0xff000000,
        .mult_parent        = {"osc_clk", "rc_clk_src"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "pwm_clk_temp",
        .flag               = MUX | DIV,
        .clk_mux.reg_offset = REG_AON_CLK_SEL1,
        .clk_mux.mask       = 0x1000,
        .clk_div.reg_offset = REG_AON_CLK_DIV2,
        .clk_div.mask       = 0xff00,
        .mult_parent        = {"osc_clk", "rc_clk_src"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "pwm_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x40000,
        .mult_parent        = {"ahb_clk"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "rc_xtal_clk",
        .flag               = DIV,
        .clk_div.reg_offset = REG_AON_CLK_DIV2,
        .clk_div.mask       = 0xff000000,
        .mult_parent        = {"osc_clk"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "rst_clk_in",
        .flag               = MUX,
        .clk_mux.reg_offset = REG_AON_CLK_SEL1,
        .clk_mux.mask       = 0x10000000,
        .mult_parent        = {"osc_clk", "rc_clk_src"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "spinlock_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x800,
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
        .mult_parent        = {"ahb_clk"},
    },
    {
        .name               = "timer_clk_temp",
        .flag               = MUX | DIV,
        .clk_mux.reg_offset = REG_AON_CLK_SEL0,
        .clk_mux.mask       = 0x1000000,
        .clk_div.reg_offset = REG_AON_CLK_DIV0,
        .clk_div.mask       = 0xff000000,
        .mult_parent        = {"osc_clk", "rc_clk_src"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "timer_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x400,
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
        .mult_parent        = {"ahb_clk"},
    },
    {
        .name               = "uart_clk_temp",
        .flag               = MUX | DIV,
        .clk_mux.reg_offset = REG_AON_CLK_SEL0,
        .clk_mux.mask       = 0x10000,
        .clk_div.reg_offset = REG_AON_CLK_DIV0,
        .clk_div.mask       = 0xff0000,
        .mult_parent        = {"osc_clk", "rc_clk_src"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "uart_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x200,
        .mult_parent        = {"ahb_clk"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "aon_wdt_clk",
        .flag               = DIV,
        .clk_div.reg_offset = REG_AON_CLK_DIV1,
        .clk_div.mask       = 0xff0000,
        .mult_parent        = {"ahb_clk"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
    {
        .name               = "aon_wdt_pclk",
        .flag               = GATE,
        .clk_gate.reg_offset = REG_AON_CLK_GATE0,
        .clk_gate.value     = DEFAULT,
        .clk_gate.mask      = 0x80,
        .mult_parent        = {"ahb_clk"},
        .clk_config         = UNCONFIG,
        .is_aon_clk         = 1,
    },
};
unsigned int fh_clock_cfg_count = ARRAY_SIZE(fh_clk_list);
#endif
