#ifndef __VPU_CHN_YUV_TYPE_H__
#define __VPU_CHN_YUV_TYPE_H__

#ifdef VIDEO_GRP0
#ifdef FH_CH0_USING_SCAN_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH0_USING_BLK_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_BLK
#endif

#ifdef FH_CH0_USING_TILE192_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH0_USING_TILE224_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH0_USING_TILE256_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH0_USING_TILE256_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH0_USING_YUYV_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH0_USING_NV16_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_NV16
#endif

#ifdef FH_CH0_USING_YVYU_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_YVYU
#endif

#ifndef CH0_YUV_TYPE_G0
#define CH0_YUV_TYPE_G0 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH1_USING_SCAN_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH1_USING_BLK_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_BLK
#endif

#ifdef FH_CH1_USING_TILE192_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH1_USING_TILE224_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH1_USING_TILE256_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH1_USING_YUYV_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH1_USING_NV16_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_NV16
#endif

#ifndef CH1_YUV_TYPE_G0
#define CH1_YUV_TYPE_G0 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH2_USING_RGB888_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_RGB888
#endif

#ifdef FH_CH2_USING_YUYV_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH2_USING_Y_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_Y
#endif

#ifndef CH2_YUV_TYPE_G0
#define CH2_YUV_TYPE_G0 VPU_VOMODE_RGB888
#endif

#endif // VIDEO_GRP0

#ifdef VIDEO_GRP1
#ifdef FH_CH0_USING_SCAN_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH0_USING_BLK_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_BLK
#endif

#ifdef FH_CH0_USING_TILE192_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH0_USING_TILE224_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH0_USING_TILE256_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH0_USING_YUYV_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH0_USING_NV16_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_NV16
#endif

#ifdef FH_CH0_USING_YVYU_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_YVYU
#endif

#ifndef CH0_YUV_TYPE_G1
#define CH0_YUV_TYPE_G1 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH1_USING_SCAN_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH1_USING_BLK_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_BLK
#endif

#ifdef FH_CH1_USING_TILE192_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_TILE192
#endif

#ifdef FH_CH1_USING_TILE224_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_TILE224
#endif

#ifdef FH_CH1_USING_TILE256_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_TILE256
#endif

#ifdef FH_CH1_USING_YUYV_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH1_USING_NV16_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_NV16
#endif

#ifndef CH1_YUV_TYPE_G1
#define CH1_YUV_TYPE_G1 VPU_VOMODE_SCAN
#endif

#ifdef FH_CH2_USING_RGB888_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_RGB888
#endif

#ifdef FH_CH2_USING_YUYV_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_YUYV
#endif

#ifdef FH_CH2_USING_Y_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_Y
#endif

#ifndef CH2_YUV_TYPE_G1
#define CH2_YUV_TYPE_G1 VPU_VOMODE_RGB888
#endif

#endif // VIDEO_GRP1

#endif // __VPU_CHN_YUV_TYPE_H__
