 /* File      : user_string.c
 * This file is automatically generated by OriginGen.py & OsdStringGenIPC.py
 *
 * Copyright (c) 2023 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Generated at:2024-04-12 16:11:36
 */
#include "user_string.h"
#include "user_menu.h"

char str_main[MAX_COMPONENT_PER_NUM][MAX_STR_LEN] = {
    "主菜单","曝光","白平衡","日夜切换","图像增强","视频输出","语言","英文","中文","恢复出厂设置","保存退出","退出",
};
char str_ae[MAX_COMPONENT_PER_NUM][MAX_STR_LEN] = {
    "曝光","亮度","曝光模式","全局","背光补偿","强度","增益","关","弱","中","强","返回",
};
char str_awb[MAX_COMPONENT_PER_NUM][MAX_STR_LEN] = {
    "白平衡","模式","自动跟踪白平衡","手动白平衡","红增益","蓝增益","返回",
};
char str_dayNight[MAX_COMPONENT_PER_NUM][MAX_STR_LEN] = {
    "日夜切换","模式","外部","自动","彩色","黑白","红外","智能红外","开","关","返回",
};
char str_imageEnhance[MAX_COMPONENT_PER_NUM][MAX_STR_LEN] = {
    "图像增强","对比度","手动","自动","","锐度","手动","自动","","饱和度","手动","自动","","返回",
};
char str_videoOutput[MAX_COMPONENT_PER_NUM][MAX_STR_LEN] = {
    "视频输出","模式","CVBS","TVI","CVI","AHD","制式","PAL","NTSC","制式","1080P25","1080P30","720P25","720P30","制式","1080P25","1080P30","720P25","720P30","制式","1080P25","1080P30","720P25","720P30","保存并重启","返回",
};
char str_sleep[MAX_COMPONENT_PER_NUM][MAX_STR_LEN] = {
    "","","","INTT",
};
char str_confirm[MAX_COMPONENT_PER_NUM][MAX_STR_LEN] = {
    "是否恢复出厂设置","否","是",
};

char *osd_string_index[MENU_NUM] = {
    str_main[0],
    str_ae[0],
    str_awb[0],
    str_dayNight[0],
    str_imageEnhance[0],
    str_videoOutput[0],
    str_sleep[0],
    str_confirm[0],
};