/**
 * File      : user_menu.h
 * This file is automatically generated by OriginGen.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Generated at:2024-04-12 16:11:36
 */

#ifndef _USER_MENU_H_
#define _USER_MENU_H_

#define MENU_NUM 8
enum {
    MENU_MAIN,
    MENU_AE,
    MENU_AWB,
    MENU_DAYNIGHT,
    MENU_IMAGEENHANCE,
    MENU_VIDEOOUTPUT,
    MENU_SLEEP,
    MENU_CONFIRM,
};

void initializeUserMenu();

#endif