/**
 * File      : user_menu.c
 * This file is automatically generated by OriginGen.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Generated at: 2024-04-12 16:11:36
 */

#include "menu/menu_list.h"

void initializeUserMenu() {
    menuMain_initialize();
    menuAe_initialize();
    menuAwb_initialize();
    menuDayNight_initialize();
    menuImageEnhance_initialize();
    menuVideoOutput_initialize();
    menuSleep_initialize();
    menuConfirm_initialize();
};
