#menu2
#language: English

[ae]
type=menu
name=曝光

[luma]
type=scrollbar
name=亮度
min=0
max=100
step=1
focused=1

[aeMode]
name=曝光模式
type=combobox
text=全局;背光补偿

[lv]
name=强度
type=scrollbar
min=0
max=8
step=1
enable=0

[aeGain]
type=combobox
name=增益
text=关;弱;中;强

[aeMenuReturn]
type=button
name=返回
jumpto=main
buttontype = 1