#awb
#language: English

[awb]
type=menu
name=白平衡

[awbMode]
type=combobox
name=模式
text=自动跟踪白平衡;手动白平衡
focused=1

[rgain]
type=scrollbar
name=红增益
min=0
max=100
step=1

[bgain]
type=scrollbar
name=蓝增益
min=0
max=100
step=1

[awbMenuReturn]
type=button
name=返回
jumpto=main
buttontype = 1