#menu1
#language: English

[confirm]
type=menu
name=是否恢复出厂设置
autoorder=0

[no]
type=button
name=否
x=1
y=2
jumpto=main
buttontype=0
focused=1

[yes]
type=button
name=是
x=1
y=3
jumpto=sleep
buttontype=0



