#menu1
#language: English

[dayNight]
type=menu
name=日夜切换

[dayNightMode]
type=combobox
name=模式
text=外部;自动;彩色;黑白
focused=1

[infraRed]
type=combobox
name=红外
text=智能红外;开;关

[dayNightReturn]
type=button
name=返回
jumpto=main
buttontype = 1