#menu1
#language: English

[sleep]
type=menu
name=
autoorder=0


[awaken]
type=button
name=
focused=1
jumpto=main
buttontype = 1
visible=0

[aeStatus]
type=textbox
name=
mode=1
x=6
y=15
selectable=0

[aeStatusText]
type=textbox
name=INTT
mode=0
x=1
y=15
selectable=0






