/**
 * File      : menu_videoOutput.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_VIDEOOUTPUT_H_
#define _MENU_VIDEOOUTPUT_H_

#include "../../component/osd_components.h"

extern menu_t menuVideoOutput;
extern combobox_t comboboxHd;
extern combobox_t comboboxFormatCvbs;
extern combobox_t comboboxFormatTvi;
extern combobox_t comboboxFormatCvi;
extern combobox_t comboboxFormatAhd;
extern button_t buttonApplyNReboot;
extern button_t buttonVideoOutputReturn;

void menuVideoOutput_initialize(void);

#endif  // _MENU_VIDEOOUTPUT_H_
