/**
 * File      : menu_imageEnhance.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "menu_imageEnhance.h"
#include "../callback/menu_imageEnhance_callback.h"
#include "../menu/configure.h"
#include "../user_menu.h"

/**************************************
 * 控件声明
 *************************************/
menu_t menuImageEnhance;
combobox_t comboboxContrastMode;
scrollbar_t scrollbarContrast;
combobox_t comboboxSharpnessMode;
scrollbar_t scrollbarSharpness;
combobox_t comboboxSaturateMode;
scrollbar_t scrollbarSaturate;
button_t buttonImageEnhanceReturn;

#define NUM_BASE (0)
#define NUM_menuImageEnhance (1)
#define NUM_comboboxContrastMode (3)
#define NUM_scrollbarContrast (1)
#define NUM_comboboxSharpnessMode (3)
#define NUM_scrollbarSharpness (1)
#define NUM_comboboxSaturateMode (3)
#define NUM_scrollbarSaturate (1)
#define NUM_buttonImageEnhanceReturn (1)

#define ID_BASE (0)
#define ID_menuImageEnhance (ID_BASE + NUM_BASE)
#define ID_comboboxContrastMode (ID_menuImageEnhance + NUM_menuImageEnhance)
#define ID_scrollbarContrast (ID_comboboxContrastMode + NUM_comboboxContrastMode)
#define ID_comboboxSharpnessMode (ID_scrollbarContrast + NUM_scrollbarContrast)
#define ID_scrollbarSharpness (ID_comboboxSharpnessMode + NUM_comboboxSharpnessMode)
#define ID_comboboxSaturateMode (ID_scrollbarSharpness + NUM_scrollbarSharpness)
#define ID_scrollbarSaturate (ID_comboboxSaturateMode + NUM_comboboxSaturateMode)
#define ID_buttonImageEnhanceReturn (ID_scrollbarSaturate + NUM_scrollbarSaturate)

/**************************************
 * 控件初始化
 *************************************/
static void menuImageEnhance_init(void) {
    menu_t *self = &menuImageEnhance;
    menu_conf_t *param = &defaultConf;
    menu_configure(self, param);
    menu_setId(self, MENU_IMAGEENHANCE);
    obj_setId(&self->base, ID_menuImageEnhance);
    
}

static void comboboxContrastMode_init(void) {
    combobox_t *self = &comboboxContrastMode;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxContrastMode - 1);
    obj_setId(&self->base, ID_comboboxContrastMode);
    obj_setFocused(&self->base, 1);
}

static void scrollbarContrast_init(void) {
    scrollbar_t *self = &scrollbarContrast;
    menu_conf_t *param = &defaultConf;
    scrollbar_configure(self, param);
    scrollbar_setMin(self, 0);
    scrollbar_setMax(self, 10);
    scrollbar_setStep(self, 1);
    obj_setId(&self->base, ID_scrollbarContrast);
    obj_setEnable(&self->base, 0);
}

static void comboboxSharpnessMode_init(void) {
    combobox_t *self = &comboboxSharpnessMode;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxSharpnessMode - 1);
    obj_setId(&self->base, ID_comboboxSharpnessMode);
}

static void scrollbarSharpness_init(void) {
    scrollbar_t *self = &scrollbarSharpness;
    menu_conf_t *param = &defaultConf;
    scrollbar_configure(self, param);
    scrollbar_setMin(self, 0);
    scrollbar_setMax(self, 10);
    scrollbar_setStep(self, 1);
    obj_setId(&self->base, ID_scrollbarSharpness);
    obj_setEnable(&self->base, 0);
}

static void comboboxSaturateMode_init(void) {
    combobox_t *self = &comboboxSaturateMode;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxSaturateMode - 1);
    obj_setId(&self->base, ID_comboboxSaturateMode);
}

static void scrollbarSaturate_init(void) {
    scrollbar_t *self = &scrollbarSaturate;
    menu_conf_t *param = &defaultConf;
    scrollbar_configure(self, param);
    scrollbar_setMin(self, 0);
    scrollbar_setMax(self, 10);
    scrollbar_setStep(self, 1);
    obj_setId(&self->base, ID_scrollbarSaturate);
    obj_setEnable(&self->base, 0);
}

static void buttonImageEnhanceReturn_init(void) {
    button_t *self = &buttonImageEnhanceReturn;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuMain;
    button_setJumpTo(self, &menuMain.base);
    button_setType(self, NORMAL);
    obj_setId(&self->base, ID_buttonImageEnhanceReturn);
}

/**************************************
 * 菜单初始化
 *************************************/
void menuImageEnhance_initialize(void) {
    menuImageEnhance_init();
    comboboxContrastMode_init();
    scrollbarContrast_init();
    comboboxSharpnessMode_init();
    scrollbarSharpness_init();
    comboboxSaturateMode_init();
    scrollbarSaturate_init();
    buttonImageEnhanceReturn_init();

    obj_adopt(&menuImageEnhance.base, &comboboxContrastMode.base);
    obj_append(&comboboxContrastMode.base, &scrollbarContrast.base);
    obj_append(&scrollbarContrast.base, &comboboxSharpnessMode.base);
    obj_append(&comboboxSharpnessMode.base, &scrollbarSharpness.base);
    obj_append(&scrollbarSharpness.base, &comboboxSaturateMode.base);
    obj_append(&comboboxSaturateMode.base, &scrollbarSaturate.base);
    obj_append(&scrollbarSaturate.base, &buttonImageEnhanceReturn.base);

    menu_imageEnhance_register();
}
