/**
 * File      : menu_dayNight.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_DAYNIGHT_H_
#define _MENU_DAYNIGHT_H_

#include "../../component/osd_components.h"

extern menu_t menuDayNight;
extern combobox_t comboboxDayNightMode;
extern combobox_t comboboxInfraRed;
extern button_t buttonDayNightReturn;

void menuDayNight_initialize(void);

#endif  // _MENU_DAYNIGHT_H_
