/**
 * File      : menu_sleep.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "menu_sleep.h"
#include "../callback/menu_sleep_callback.h"
#include "../menu/configure.h"
#include "../user_menu.h"

/**************************************
 * 控件声明
 *************************************/
menu_t menuSleep;
button_t buttonAwaken;
textbox_t textboxAeStatus;
textbox_t textboxAeStatusText;

#define NUM_BASE (0)
#define NUM_menuSleep (1)
#define NUM_buttonAwaken (1)
#define NUM_textboxAeStatus (1)
#define NUM_textboxAeStatusText (1)

#define ID_BASE (0)
#define ID_menuSleep (ID_BASE + NUM_BASE)
#define ID_buttonAwaken (ID_menuSleep + NUM_menuSleep)
#define ID_textboxAeStatus (ID_buttonAwaken + NUM_buttonAwaken)
#define ID_textboxAeStatusText (ID_textboxAeStatus + NUM_textboxAeStatus)

/**************************************
 * 控件初始化
 *************************************/
static void menuSleep_init(void) {
    menu_t *self = &menuSleep;
    menu_conf_t *param = &defaultConf;
    menu_configure(self, param);
    menu_setId(self, MENU_SLEEP);
    menu_setAutoOrder(self, 0);
    obj_setId(&self->base, ID_menuSleep);
    
}

static void buttonAwaken_init(void) {
    button_t *self = &buttonAwaken;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuMain;
    button_setJumpTo(self, &menuMain.base);
    button_setType(self, NORMAL);
    obj_setId(&self->base, ID_buttonAwaken);
    obj_setVisible(&self->base, 0);
    obj_setFocused(&self->base, 1);
}

static void textboxAeStatus_init(void) {
    textbox_t *self = &textboxAeStatus;
    menu_conf_t *param = &defaultConf;
    textbox_configure(self, param);
    textbox_setMode(self, TEXT_CHANGE);
    obj_setId(&self->base, ID_textboxAeStatus);
    obj_setOffsetX(&self->base, 6);
    obj_setOffsetY(&self->base, 15);
    obj_setSelectable(&self->base, 0);
}

static void textboxAeStatusText_init(void) {
    textbox_t *self = &textboxAeStatusText;
    menu_conf_t *param = &defaultConf;
    textbox_configure(self, param);
    textbox_setMode(self, TEXT_DEFAULT);
    obj_setId(&self->base, ID_textboxAeStatusText);
    obj_setOffsetX(&self->base, 1);
    obj_setOffsetY(&self->base, 15);
    obj_setSelectable(&self->base, 0);
}

/**************************************
 * 菜单初始化
 *************************************/
void menuSleep_initialize(void) {
    menuSleep_init();
    buttonAwaken_init();
    textboxAeStatus_init();
    textboxAeStatusText_init();

    obj_adopt(&menuSleep.base, &buttonAwaken.base);
    obj_append(&buttonAwaken.base, &textboxAeStatus.base);
    obj_append(&textboxAeStatus.base, &textboxAeStatusText.base);

    menu_sleep_register();
}
