/**
 * File      : menu_main.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "menu_main.h"
#include "../callback/menu_main_callback.h"
#include "../menu/configure.h"
#include "../user_menu.h"

/**************************************
 * 控件声明
 *************************************/
menu_t menuMain;
button_t buttonAe;
button_t buttonAwb;
button_t buttonDayNight;
button_t buttonImageEnhance;
button_t buttonVideoOutput;
combobox_t comboboxLanguage;
button_t buttonReset;
button_t buttonSaveExit;
button_t buttonExit;

#define NUM_BASE (0)
#define NUM_menuMain (1)
#define NUM_buttonAe (1)
#define NUM_buttonAwb (1)
#define NUM_buttonDayNight (1)
#define NUM_buttonImageEnhance (1)
#define NUM_buttonVideoOutput (1)
#define NUM_comboboxLanguage (3)
#define NUM_buttonReset (1)
#define NUM_buttonSaveExit (1)
#define NUM_buttonExit (1)

#define ID_BASE (0)
#define ID_menuMain (ID_BASE + NUM_BASE)
#define ID_buttonAe (ID_menuMain + NUM_menuMain)
#define ID_buttonAwb (ID_buttonAe + NUM_buttonAe)
#define ID_buttonDayNight (ID_buttonAwb + NUM_buttonAwb)
#define ID_buttonImageEnhance (ID_buttonDayNight + NUM_buttonDayNight)
#define ID_buttonVideoOutput (ID_buttonImageEnhance + NUM_buttonImageEnhance)
#define ID_comboboxLanguage (ID_buttonVideoOutput + NUM_buttonVideoOutput)
#define ID_buttonReset (ID_comboboxLanguage + NUM_comboboxLanguage)
#define ID_buttonSaveExit (ID_buttonReset + NUM_buttonReset)
#define ID_buttonExit (ID_buttonSaveExit + NUM_buttonSaveExit)

/**************************************
 * 控件初始化
 *************************************/
static void menuMain_init(void) {
    menu_t *self = &menuMain;
    menu_conf_t *param = &defaultConf;
    menu_configure(self, param);
    menu_setId(self, MENU_MAIN);
    menu_setAutoOrder(self, 0);
    obj_setId(&self->base, ID_menuMain);
    
}

static void buttonAe_init(void) {
    button_t *self = &buttonAe;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuAe;
    button_setJumpTo(self, &menuAe.base);
    button_setType(self, TO_SUBMENU);
    obj_setId(&self->base, ID_buttonAe);
    obj_setOffsetY(&self->base, 1);
    obj_setFocused(&self->base, 1);
}

static void buttonAwb_init(void) {
    button_t *self = &buttonAwb;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuAwb;
    button_setJumpTo(self, &menuAwb.base);
    button_setType(self, TO_SUBMENU);
    obj_setId(&self->base, ID_buttonAwb);
    obj_setOffsetY(&self->base, 2);
}

static void buttonDayNight_init(void) {
    button_t *self = &buttonDayNight;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuDayNight;
    button_setJumpTo(self, &menuDayNight.base);
    button_setType(self, TO_SUBMENU);
    obj_setId(&self->base, ID_buttonDayNight);
    obj_setOffsetY(&self->base, 3);
}

static void buttonImageEnhance_init(void) {
    button_t *self = &buttonImageEnhance;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuImageEnhance;
    button_setJumpTo(self, &menuImageEnhance.base);
    button_setType(self, TO_SUBMENU);
    obj_setId(&self->base, ID_buttonImageEnhance);
    obj_setOffsetY(&self->base, 4);
}

static void buttonVideoOutput_init(void) {
    button_t *self = &buttonVideoOutput;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuVideoOutput;
    button_setJumpTo(self, &menuVideoOutput.base);
    button_setType(self, TO_SUBMENU);
    obj_setId(&self->base, ID_buttonVideoOutput);
    obj_setOffsetY(&self->base, 5);
}

static void comboboxLanguage_init(void) {
    combobox_t *self = &comboboxLanguage;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxLanguage - 1);
    obj_setId(&self->base, ID_comboboxLanguage);
    obj_setOffsetY(&self->base, 6);
}

static void buttonReset_init(void) {
    button_t *self = &buttonReset;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuConfirm;
    button_setJumpTo(self, &menuConfirm.base);
    button_setType(self, NORMAL);
    obj_setId(&self->base, ID_buttonReset);
    obj_setOffsetY(&self->base, 8);
}

static void buttonSaveExit_init(void) {
    button_t *self = &buttonSaveExit;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuSleep;
    button_setJumpTo(self, &menuSleep.base);
    button_setType(self, NORMAL);
    obj_setId(&self->base, ID_buttonSaveExit);
    obj_setOffsetY(&self->base, 9);
}

static void buttonExit_init(void) {
    button_t *self = &buttonExit;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuSleep;
    button_setJumpTo(self, &menuSleep.base);
    button_setType(self, NORMAL);
    obj_setId(&self->base, ID_buttonExit);
    obj_setOffsetY(&self->base, 10);
}

/**************************************
 * 菜单初始化
 *************************************/
void menuMain_initialize(void) {
    menuMain_init();
    buttonAe_init();
    buttonAwb_init();
    buttonDayNight_init();
    buttonImageEnhance_init();
    buttonVideoOutput_init();
    comboboxLanguage_init();
    buttonReset_init();
    buttonSaveExit_init();
    buttonExit_init();

    obj_adopt(&menuMain.base, &buttonAe.base);
    obj_append(&buttonAe.base, &buttonAwb.base);
    obj_append(&buttonAwb.base, &buttonDayNight.base);
    obj_append(&buttonDayNight.base, &buttonImageEnhance.base);
    obj_append(&buttonImageEnhance.base, &buttonVideoOutput.base);
    obj_append(&buttonVideoOutput.base, &comboboxLanguage.base);
    obj_append(&comboboxLanguage.base, &buttonReset.base);
    obj_append(&buttonReset.base, &buttonSaveExit.base);
    obj_append(&buttonSaveExit.base, &buttonExit.base);

    menu_main_register();
}
