/**
 * File      : menu_confirm.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_CONFIRM_H_
#define _MENU_CONFIRM_H_

#include "../../component/osd_components.h"

extern menu_t menuConfirm;
extern button_t buttonNo;
extern button_t buttonYes;

void menuConfirm_initialize(void);

#endif  // _MENU_CONFIRM_H_
