/**
 * File      : menu_awb.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_AWB_H_
#define _MENU_AWB_H_

#include "../../component/osd_components.h"

extern menu_t menuAwb;
extern combobox_t comboboxAwbMode;
extern scrollbar_t scrollbarRgain;
extern scrollbar_t scrollbarBgain;
extern button_t buttonAwbMenuReturn;

void menuAwb_initialize(void);

#endif  // _MENU_AWB_H_
