/**
 * File      : menu_awb.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "menu_awb.h"
#include "../callback/menu_awb_callback.h"
#include "../menu/configure.h"
#include "../user_menu.h"

/**************************************
 * 控件声明
 *************************************/
menu_t menuAwb;
combobox_t comboboxAwbMode;
scrollbar_t scrollbarRgain;
scrollbar_t scrollbarBgain;
button_t buttonAwbMenuReturn;

#define NUM_BASE (0)
#define NUM_menuAwb (1)
#define NUM_comboboxAwbMode (3)
#define NUM_scrollbarRgain (1)
#define NUM_scrollbarBgain (1)
#define NUM_buttonAwbMenuReturn (1)

#define ID_BASE (0)
#define ID_menuAwb (ID_BASE + NUM_BASE)
#define ID_comboboxAwbMode (ID_menuAwb + NUM_menuAwb)
#define ID_scrollbarRgain (ID_comboboxAwbMode + NUM_comboboxAwbMode)
#define ID_scrollbarBgain (ID_scrollbarRgain + NUM_scrollbarRgain)
#define ID_buttonAwbMenuReturn (ID_scrollbarBgain + NUM_scrollbarBgain)

/**************************************
 * 控件初始化
 *************************************/
static void menuAwb_init(void) {
    menu_t *self = &menuAwb;
    menu_conf_t *param = &defaultConf;
    menu_configure(self, param);
    menu_setId(self, MENU_AWB);
    obj_setId(&self->base, ID_menuAwb);
    
}

static void comboboxAwbMode_init(void) {
    combobox_t *self = &comboboxAwbMode;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxAwbMode - 1);
    obj_setId(&self->base, ID_comboboxAwbMode);
    obj_setFocused(&self->base, 1);
}

static void scrollbarRgain_init(void) {
    scrollbar_t *self = &scrollbarRgain;
    menu_conf_t *param = &defaultConf;
    scrollbar_configure(self, param);
    scrollbar_setMin(self, 0);
    scrollbar_setMax(self, 100);
    scrollbar_setStep(self, 1);
    obj_setId(&self->base, ID_scrollbarRgain);
}

static void scrollbarBgain_init(void) {
    scrollbar_t *self = &scrollbarBgain;
    menu_conf_t *param = &defaultConf;
    scrollbar_configure(self, param);
    scrollbar_setMin(self, 0);
    scrollbar_setMax(self, 100);
    scrollbar_setStep(self, 1);
    obj_setId(&self->base, ID_scrollbarBgain);
}

static void buttonAwbMenuReturn_init(void) {
    button_t *self = &buttonAwbMenuReturn;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuMain;
    button_setJumpTo(self, &menuMain.base);
    button_setType(self, NORMAL);
    obj_setId(&self->base, ID_buttonAwbMenuReturn);
}

/**************************************
 * 菜单初始化
 *************************************/
void menuAwb_initialize(void) {
    menuAwb_init();
    comboboxAwbMode_init();
    scrollbarRgain_init();
    scrollbarBgain_init();
    buttonAwbMenuReturn_init();

    obj_adopt(&menuAwb.base, &comboboxAwbMode.base);
    obj_append(&comboboxAwbMode.base, &scrollbarRgain.base);
    obj_append(&scrollbarRgain.base, &scrollbarBgain.base);
    obj_append(&scrollbarBgain.base, &buttonAwbMenuReturn.base);

    menu_awb_register();
}
