/**
 * File      : menu_dayNight.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "menu_dayNight.h"
#include "../callback/menu_dayNight_callback.h"
#include "../menu/configure.h"
#include "../user_menu.h"

/**************************************
 * 控件声明
 *************************************/
menu_t menuDayNight;
combobox_t comboboxDayNightMode;
combobox_t comboboxInfraRed;
button_t buttonDayNightReturn;

#define NUM_BASE (0)
#define NUM_menuDayNight (1)
#define NUM_comboboxDayNightMode (5)
#define NUM_comboboxInfraRed (4)
#define NUM_buttonDayNightReturn (1)

#define ID_BASE (0)
#define ID_menuDayNight (ID_BASE + NUM_BASE)
#define ID_comboboxDayNightMode (ID_menuDayNight + NUM_menuDayNight)
#define ID_comboboxInfraRed (ID_comboboxDayNightMode + NUM_comboboxDayNightMode)
#define ID_buttonDayNightReturn (ID_comboboxInfraRed + NUM_comboboxInfraRed)

/**************************************
 * 控件初始化
 *************************************/
static void menuDayNight_init(void) {
    menu_t *self = &menuDayNight;
    menu_conf_t *param = &defaultConf;
    menu_configure(self, param);
    menu_setId(self, MENU_DAYNIGHT);
    obj_setId(&self->base, ID_menuDayNight);
    
}

static void comboboxDayNightMode_init(void) {
    combobox_t *self = &comboboxDayNightMode;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxDayNightMode - 1);
    obj_setId(&self->base, ID_comboboxDayNightMode);
    obj_setFocused(&self->base, 1);
}

static void comboboxInfraRed_init(void) {
    combobox_t *self = &comboboxInfraRed;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxInfraRed - 1);
    obj_setId(&self->base, ID_comboboxInfraRed);
}

static void buttonDayNightReturn_init(void) {
    button_t *self = &buttonDayNightReturn;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuMain;
    button_setJumpTo(self, &menuMain.base);
    button_setType(self, NORMAL);
    obj_setId(&self->base, ID_buttonDayNightReturn);
}

/**************************************
 * 菜单初始化
 *************************************/
void menuDayNight_initialize(void) {
    menuDayNight_init();
    comboboxDayNightMode_init();
    comboboxInfraRed_init();
    buttonDayNightReturn_init();

    obj_adopt(&menuDayNight.base, &comboboxDayNightMode.base);
    obj_append(&comboboxDayNightMode.base, &comboboxInfraRed.base);
    obj_append(&comboboxInfraRed.base, &buttonDayNightReturn.base);

    menu_dayNight_register();
}
