/**
 * File      : menu_ae.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_AE_H_
#define _MENU_AE_H_

#include "../../component/osd_components.h"

extern menu_t menuAe;
extern scrollbar_t scrollbarLuma;
extern combobox_t comboboxAeMode;
extern scrollbar_t scrollbarLv;
extern combobox_t comboboxAeGain;
extern button_t buttonAeMenuReturn;

void menuAe_initialize(void);

#endif  // _MENU_AE_H_
