/**
 * File      : menu_list.h
 * This file is automatically generated by OriginGen.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2016 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 1.0
 * Generated at:2024-04-12 16:11:36
 */

#ifndef _MEUN_LIST_H_
#define _MEUN_LIST_H_

#include "menu_main.h"
#include "menu_ae.h"
#include "menu_awb.h"
#include "menu_dayNight.h"
#include "menu_imageEnhance.h"
#include "menu_videoOutput.h"
#include "menu_sleep.h"
#include "menu_confirm.h"
#endif // !_MEUN_LIST_H_
