/**
 * File      : menu_sleep.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_SLEEP_H_
#define _MENU_SLEEP_H_

#include "../../component/osd_components.h"

extern menu_t menuSleep;
extern button_t buttonAwaken;
extern textbox_t textboxAeStatus;
extern textbox_t textboxAeStatusText;

void menuSleep_initialize(void);

#endif  // _MENU_SLEEP_H_
