/**
 * File      : menu_ae.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "menu_ae.h"
#include "../callback/menu_ae_callback.h"
#include "../menu/configure.h"
#include "../user_menu.h"

/**************************************
 * 控件声明
 *************************************/
menu_t menuAe;
scrollbar_t scrollbarLuma;
combobox_t comboboxAeMode;
scrollbar_t scrollbarLv;
combobox_t comboboxAeGain;
button_t buttonAeMenuReturn;

#define NUM_BASE (0)
#define NUM_menuAe (1)
#define NUM_scrollbarLuma (1)
#define NUM_comboboxAeMode (3)
#define NUM_scrollbarLv (1)
#define NUM_comboboxAeGain (5)
#define NUM_buttonAeMenuReturn (1)

#define ID_BASE (0)
#define ID_menuAe (ID_BASE + NUM_BASE)
#define ID_scrollbarLuma (ID_menuAe + NUM_menuAe)
#define ID_comboboxAeMode (ID_scrollbarLuma + NUM_scrollbarLuma)
#define ID_scrollbarLv (ID_comboboxAeMode + NUM_comboboxAeMode)
#define ID_comboboxAeGain (ID_scrollbarLv + NUM_scrollbarLv)
#define ID_buttonAeMenuReturn (ID_comboboxAeGain + NUM_comboboxAeGain)

/**************************************
 * 控件初始化
 *************************************/
static void menuAe_init(void) {
    menu_t *self = &menuAe;
    menu_conf_t *param = &defaultConf;
    menu_configure(self, param);
    menu_setId(self, MENU_AE);
    obj_setId(&self->base, ID_menuAe);
    
}

static void scrollbarLuma_init(void) {
    scrollbar_t *self = &scrollbarLuma;
    menu_conf_t *param = &defaultConf;
    scrollbar_configure(self, param);
    scrollbar_setMin(self, 0);
    scrollbar_setMax(self, 100);
    scrollbar_setStep(self, 1);
    obj_setId(&self->base, ID_scrollbarLuma);
    obj_setFocused(&self->base, 1);
}

static void comboboxAeMode_init(void) {
    combobox_t *self = &comboboxAeMode;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxAeMode - 1);
    obj_setId(&self->base, ID_comboboxAeMode);
}

static void scrollbarLv_init(void) {
    scrollbar_t *self = &scrollbarLv;
    menu_conf_t *param = &defaultConf;
    scrollbar_configure(self, param);
    scrollbar_setMin(self, 0);
    scrollbar_setMax(self, 8);
    scrollbar_setStep(self, 1);
    obj_setId(&self->base, ID_scrollbarLv);
    obj_setEnable(&self->base, 0);
}

static void comboboxAeGain_init(void) {
    combobox_t *self = &comboboxAeGain;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxAeGain - 1);
    obj_setId(&self->base, ID_comboboxAeGain);
}

static void buttonAeMenuReturn_init(void) {
    button_t *self = &buttonAeMenuReturn;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuMain;
    button_setJumpTo(self, &menuMain.base);
    button_setType(self, NORMAL);
    obj_setId(&self->base, ID_buttonAeMenuReturn);
}

/**************************************
 * 菜单初始化
 *************************************/
void menuAe_initialize(void) {
    menuAe_init();
    scrollbarLuma_init();
    comboboxAeMode_init();
    scrollbarLv_init();
    comboboxAeGain_init();
    buttonAeMenuReturn_init();

    obj_adopt(&menuAe.base, &scrollbarLuma.base);
    obj_append(&scrollbarLuma.base, &comboboxAeMode.base);
    obj_append(&comboboxAeMode.base, &scrollbarLv.base);
    obj_append(&scrollbarLv.base, &comboboxAeGain.base);
    obj_append(&comboboxAeGain.base, &buttonAeMenuReturn.base);

    menu_ae_register();
}
