/**
 * File      : menu_imageEnhance.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_IMAGEENHANCE_H_
#define _MENU_IMAGEENHANCE_H_

#include "../../component/osd_components.h"

extern menu_t menuImageEnhance;
extern combobox_t comboboxContrastMode;
extern scrollbar_t scrollbarContrast;
extern combobox_t comboboxSharpnessMode;
extern scrollbar_t scrollbarSharpness;
extern combobox_t comboboxSaturateMode;
extern scrollbar_t scrollbarSaturate;
extern button_t buttonImageEnhanceReturn;

void menuImageEnhance_initialize(void);

#endif  // _MENU_IMAGEENHANCE_H_
