/**
 * File      : menu_confirm.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "menu_confirm.h"
#include "../callback/menu_confirm_callback.h"
#include "../menu/configure.h"
#include "../user_menu.h"

/**************************************
 * 控件声明
 *************************************/
menu_t menuConfirm;
button_t buttonNo;
button_t buttonYes;

#define NUM_BASE (0)
#define NUM_menuConfirm (1)
#define NUM_buttonNo (1)
#define NUM_buttonYes (1)

#define ID_BASE (0)
#define ID_menuConfirm (ID_BASE + NUM_BASE)
#define ID_buttonNo (ID_menuConfirm + NUM_menuConfirm)
#define ID_buttonYes (ID_buttonNo + NUM_buttonNo)

/**************************************
 * 控件初始化
 *************************************/
static void menuConfirm_init(void) {
    menu_t *self = &menuConfirm;
    menu_conf_t *param = &defaultConf;
    menu_configure(self, param);
    menu_setId(self, MENU_CONFIRM);
    menu_setAutoOrder(self, 0);
    obj_setId(&self->base, ID_menuConfirm);

}

static void buttonNo_init(void) {
    button_t *self = &buttonNo;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuMain;
    button_setJumpTo(self, &menuMain.base);
    button_setType(self, TO_SUBMENU);
    obj_setId(&self->base, ID_buttonNo);
    obj_setOffsetX(&self->base, 1);
    obj_setOffsetY(&self->base, 2);
    obj_setFocused(&self->base, 1);
}

static void buttonYes_init(void) {
    button_t *self = &buttonYes;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuSleep;
    button_setJumpTo(self, &menuSleep.base);
    button_setType(self, TO_SUBMENU);
    obj_setId(&self->base, ID_buttonYes);
    obj_setOffsetX(&self->base, 1);
    obj_setOffsetY(&self->base, 3);
}

/**************************************
 * 菜单初始化
 *************************************/
void menuConfirm_initialize(void) {
    menuConfirm_init();
    buttonNo_init();
    buttonYes_init();

    obj_adopt(&menuConfirm.base, &buttonNo.base);
    obj_append(&buttonNo.base, &buttonYes.base);

    menu_confirm_register();
}
