/**
 * File      : menu_main.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_MAIN_H_
#define _MENU_MAIN_H_

#include "../../component/osd_components.h"

extern menu_t menuMain;
extern button_t buttonAe;
extern button_t buttonAwb;
extern button_t buttonDayNight;
extern button_t buttonImageEnhance;
extern button_t buttonVideoOutput;
extern combobox_t comboboxLanguage;
extern button_t buttonReset;
extern button_t buttonSaveExit;
extern button_t buttonExit;

void menuMain_initialize(void);

#endif  // _MENU_MAIN_H_
