/**
 * File      : menu_videoOutput.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "menu_videoOutput.h"
#include "../callback/menu_videoOutput_callback.h"
#include "../menu/configure.h"
#include "../user_menu.h"

/**************************************
 * 控件声明
 *************************************/
menu_t menuVideoOutput;
combobox_t comboboxHd;
combobox_t comboboxFormatCvbs;
combobox_t comboboxFormatTvi;
combobox_t comboboxFormatCvi;
combobox_t comboboxFormatAhd;
button_t buttonApplyNReboot;
button_t buttonVideoOutputReturn;

#define NUM_BASE (0)
#define NUM_menuVideoOutput (1)
#define NUM_comboboxHd (5)
#define NUM_comboboxFormatCvbs (3)
#define NUM_comboboxFormatTvi (5)
#define NUM_comboboxFormatCvi (5)
#define NUM_comboboxFormatAhd (5)
#define NUM_buttonApplyNReboot (1)
#define NUM_buttonVideoOutputReturn (1)

#define ID_BASE (0)
#define ID_menuVideoOutput (ID_BASE + NUM_BASE)
#define ID_comboboxHd (ID_menuVideoOutput + NUM_menuVideoOutput)
#define ID_comboboxFormatCvbs (ID_comboboxHd + NUM_comboboxHd)
#define ID_comboboxFormatTvi (ID_comboboxFormatCvbs + NUM_comboboxFormatCvbs)
#define ID_comboboxFormatCvi (ID_comboboxFormatTvi + NUM_comboboxFormatTvi)
#define ID_comboboxFormatAhd (ID_comboboxFormatCvi + NUM_comboboxFormatCvi)
#define ID_buttonApplyNReboot (ID_comboboxFormatAhd + NUM_comboboxFormatAhd)
#define ID_buttonVideoOutputReturn (ID_buttonApplyNReboot + NUM_buttonApplyNReboot)

/**************************************
 * 控件初始化
 *************************************/
static void menuVideoOutput_init(void) {
    menu_t *self = &menuVideoOutput;
    menu_conf_t *param = &defaultConf;
    menu_configure(self, param);
    menu_setId(self, MENU_VIDEOOUTPUT);
    obj_setId(&self->base, ID_menuVideoOutput);
    
}

static void comboboxHd_init(void) {
    combobox_t *self = &comboboxHd;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxHd - 1);
    obj_setId(&self->base, ID_comboboxHd);
    obj_setFocused(&self->base, 1);
}

static void comboboxFormatCvbs_init(void) {
    combobox_t *self = &comboboxFormatCvbs;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxFormatCvbs - 1);
    obj_setId(&self->base, ID_comboboxFormatCvbs);
}

static void comboboxFormatTvi_init(void) {
    combobox_t *self = &comboboxFormatTvi;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxFormatTvi - 1);
    obj_setId(&self->base, ID_comboboxFormatTvi);
}

static void comboboxFormatCvi_init(void) {
    combobox_t *self = &comboboxFormatCvi;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxFormatCvi - 1);
    obj_setId(&self->base, ID_comboboxFormatCvi);
}

static void comboboxFormatAhd_init(void) {
    combobox_t *self = &comboboxFormatAhd;
    menu_conf_t *param = &defaultConf;
    combobox_configure(self, param);
    combobox_setMaxNum(self, NUM_comboboxFormatAhd - 1);
    obj_setId(&self->base, ID_comboboxFormatAhd);
}

static void buttonApplyNReboot_init(void) {
    button_t *self = &buttonApplyNReboot;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuMain;
    button_setJumpTo(self, &menuMain.base);
    button_setType(self, NORMAL);
    obj_setId(&self->base, ID_buttonApplyNReboot);
    obj_setEnable(&self->base, 0);
}

static void buttonVideoOutputReturn_init(void) {
    button_t *self = &buttonVideoOutputReturn;
    menu_conf_t *param = &defaultConf;
    button_configure(self, param);
    extern menu_t menuMain;
    button_setJumpTo(self, &menuMain.base);
    button_setType(self, NORMAL);
    obj_setId(&self->base, ID_buttonVideoOutputReturn);
}

/**************************************
 * 菜单初始化
 *************************************/
void menuVideoOutput_initialize(void) {
    menuVideoOutput_init();
    comboboxHd_init();
    comboboxFormatCvbs_init();
    comboboxFormatTvi_init();
    comboboxFormatCvi_init();
    comboboxFormatAhd_init();
    buttonApplyNReboot_init();
    buttonVideoOutputReturn_init();

    obj_adopt(&menuVideoOutput.base, &comboboxHd.base);
    obj_append(&comboboxHd.base, &comboboxFormatCvbs.base);
    obj_append(&comboboxFormatCvbs.base, &comboboxFormatTvi.base);
    obj_append(&comboboxFormatTvi.base, &comboboxFormatCvi.base);
    obj_append(&comboboxFormatCvi.base, &comboboxFormatAhd.base);
    obj_append(&comboboxFormatAhd.base, &buttonApplyNReboot.base);
    obj_append(&buttonApplyNReboot.base, &buttonVideoOutputReturn.base);

    menu_videoOutput_register();
}
