/**
 * File      : menu_awb_callback.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_AWB_CALLBACK_H_
#define _MENU_AWB_CALLBACK_H_


void menu_awb_register();
// void menuAwb_onDraw(void *self);
// void comboboxAwbMode_onDataChange(void *self);
// void comboboxAwbMode_onDraw(void *self);
// void scrollbarRgain_onDataChange(void *self);
// void scrollbarRgain_onDraw(void *self);
// void scrollbarBgain_onDataChange(void *self);
// void scrollbarBgain_onDraw(void *self);
// void buttonAwbMenuReturn_onClick(void *self);

#endif  // _MENU_AWB_CALLBACK_H_
