/**
 * File      : menu_main_callback.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "../menu/menu_main.h"
#include "menu_main_callback.h"
#include "../menu/configure.h"

void menu_main_register() {
    // menu_registerDrawCallback(&menuMain, menuMain_onDraw);
    // button_registerClickCallback(&buttonAe, buttonAe_onClick);
    // button_registerClickCallback(&buttonAwb, buttonAwb_onClick);
    // button_registerClickCallback(&buttonDayNight, buttonDayNight_onClick);
    // button_registerClickCallback(&buttonImageEnhance, buttonImageEnhance_onClick);
    // button_registerClickCallback(&buttonVideoOutput, buttonVideoOutput_onClick);
    // combobox_registerDataChangeCallback(&comboboxLanguage, comboboxLanguage_onDataChange);
    // combobox_registerGetValueCallback(&comboboxLanguage, comboboxLanguage_onDraw);
    // button_registerClickCallback(&buttonReset, buttonReset_onClick);
    // button_registerClickCallback(&buttonSaveExit, buttonSaveExit_onClick);
    // button_registerClickCallback(&buttonExit, buttonExit_onClick);
}

/**************************************
 * 事件响应
 *************************************/
// void menuMain_onDraw(void *self) {
//     return;
// }

// void buttonAe_onClick(void *self) {
//     return;
// }

// void buttonAwb_onClick(void *self) {
//     return;
// }

// void buttonDayNight_onClick(void *self) {
//     return;
// }

// void buttonImageEnhance_onClick(void *self) {
//     return;
// }

// void buttonVideoOutput_onClick(void *self) {
//     return;
// }

// void comboboxLanguage_onDataChange(void *self) {
//     return;
// }

// void comboboxLanguage_onDraw(void *self) {
//     return;
// }

// void buttonReset_onClick(void *self) {
//     return;
// }

// void buttonSaveExit_onClick(void *self) {
//     return;
// }

// void buttonExit_onClick(void *self) {
//     return;
// }

