/**
 * File      : menu_videoOutput_callback.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_VIDEOOUTPUT_CALLBACK_H_
#define _MENU_VIDEOOUTPUT_CALLBACK_H_


void menu_videoOutput_register();
// void menuVideoOutput_onDraw(void *self);
// void comboboxHd_onDataChange(void *self);
// void comboboxHd_onDraw(void *self);
// void comboboxFormatCvbs_onDataChange(void *self);
// void comboboxFormatCvbs_onDraw(void *self);
// void comboboxFormatTvi_onDataChange(void *self);
// void comboboxFormatTvi_onDraw(void *self);
// void comboboxFormatCvi_onDataChange(void *self);
// void comboboxFormatCvi_onDraw(void *self);
// void comboboxFormatAhd_onDataChange(void *self);
// void comboboxFormatAhd_onDraw(void *self);
// void buttonApplyNReboot_onClick(void *self);
// void buttonVideoOutputReturn_onClick(void *self);

#endif  // _MENU_VIDEOOUTPUT_CALLBACK_H_
