/**
 * File      : menu_sleep_callback.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_SLEEP_CALLBACK_H_
#define _MENU_SLEEP_CALLBACK_H_


void menu_sleep_register();
// void menuSleep_onDraw(void *self);
// void buttonAwaken_onClick(void *self);

#endif  // _MENU_SLEEP_CALLBACK_H_
