/**
 * File      : menu_videoOutput_callback.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "../menu/menu_videoOutput.h"
#include "menu_videoOutput_callback.h"
#include "../menu/configure.h"

void menu_videoOutput_register() {
    // menu_registerDrawCallback(&menuVideoOutput, menuVideoOutput_onDraw);
    // combobox_registerDataChangeCallback(&comboboxHd, comboboxHd_onDataChange);
    // combobox_registerGetValueCallback(&comboboxHd, comboboxHd_onDraw);
    // combobox_registerDataChangeCallback(&comboboxFormatCvbs, comboboxFormatCvbs_onDataChange);
    // combobox_registerGetValueCallback(&comboboxFormatCvbs, comboboxFormatCvbs_onDraw);
    // combobox_registerDataChangeCallback(&comboboxFormatTvi, comboboxFormatTvi_onDataChange);
    // combobox_registerGetValueCallback(&comboboxFormatTvi, comboboxFormatTvi_onDraw);
    // combobox_registerDataChangeCallback(&comboboxFormatCvi, comboboxFormatCvi_onDataChange);
    // combobox_registerGetValueCallback(&comboboxFormatCvi, comboboxFormatCvi_onDraw);
    // combobox_registerDataChangeCallback(&comboboxFormatAhd, comboboxFormatAhd_onDataChange);
    // combobox_registerGetValueCallback(&comboboxFormatAhd, comboboxFormatAhd_onDraw);
    // button_registerClickCallback(&buttonApplyNReboot, buttonApplyNReboot_onClick);
    // button_registerClickCallback(&buttonVideoOutputReturn, buttonVideoOutputReturn_onClick);
}

/**************************************
 * 事件响应
 *************************************/
// void menuVideoOutput_onDraw(void *self) {
//     return;
// }

// void comboboxHd_onDataChange(void *self) {
//     return;
// }

// void comboboxHd_onDraw(void *self) {
//     return;
// }

// void comboboxFormatCvbs_onDataChange(void *self) {
//     return;
// }

// void comboboxFormatCvbs_onDraw(void *self) {
//     return;
// }

// void comboboxFormatTvi_onDataChange(void *self) {
//     return;
// }

// void comboboxFormatTvi_onDraw(void *self) {
//     return;
// }

// void comboboxFormatCvi_onDataChange(void *self) {
//     return;
// }

// void comboboxFormatCvi_onDraw(void *self) {
//     return;
// }

// void comboboxFormatAhd_onDataChange(void *self) {
//     return;
// }

// void comboboxFormatAhd_onDraw(void *self) {
//     return;
// }

// void buttonApplyNReboot_onClick(void *self) {
//     return;
// }

// void buttonVideoOutputReturn_onClick(void *self) {
//     return;
// }

