/**
 * File      : menu_confirm_callback.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "../menu/menu_confirm.h"
#include "menu_confirm_callback.h"
#include "../menu/configure.h"

void menu_confirm_register() {
    // menu_registerDrawCallback(&menuConfirm, menuConfirm_onDraw);
    // button_registerClickCallback(&buttonNo, buttonNo_onClick);
    // button_registerClickCallback(&buttonYes, buttonYes_onClick);
}

/**************************************
 * 事件响应
 *************************************/
// void menuConfirm_onDraw(void *self) {
//     return;
// }

// void buttonNo_onClick(void *self) {
//     return;
// }

// void buttonYes_onClick(void *self) {
//     return;
// }

