/**
 * File      : menu_imageEnhance_callback.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_IMAGEENHANCE_CALLBACK_H_
#define _MENU_IMAGEENHANCE_CALLBACK_H_


void menu_imageEnhance_register();
// void menuImageEnhance_onDraw(void *self);
// void comboboxContrastMode_onDataChange(void *self);
// void comboboxContrastMode_onDraw(void *self);
// void scrollbarContrast_onDataChange(void *self);
// void scrollbarContrast_onDraw(void *self);
// void comboboxSharpnessMode_onDataChange(void *self);
// void comboboxSharpnessMode_onDraw(void *self);
// void scrollbarSharpness_onDataChange(void *self);
// void scrollbarSharpness_onDraw(void *self);
// void comboboxSaturateMode_onDataChange(void *self);
// void comboboxSaturateMode_onDraw(void *self);
// void scrollbarSaturate_onDataChange(void *self);
// void scrollbarSaturate_onDraw(void *self);
// void buttonImageEnhanceReturn_onClick(void *self);

#endif  // _MENU_IMAGEENHANCE_CALLBACK_H_
