/**
 * File      : menu_ae_callback.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_AE_CALLBACK_H_
#define _MENU_AE_CALLBACK_H_


void menu_ae_register();
// void menuAe_onDraw(void *self);
// void scrollbarLuma_onDataChange(void *self);
// void scrollbarLuma_onDraw(void *self);
// void comboboxAeMode_onDataChange(void *self);
// void comboboxAeMode_onDraw(void *self);
// void scrollbarLv_onDataChange(void *self);
// void scrollbarLv_onDraw(void *self);
// void comboboxAeGain_onDataChange(void *self);
// void comboboxAeGain_onDraw(void *self);
// void buttonAeMenuReturn_onClick(void *self);

#endif  // _MENU_AE_CALLBACK_H_
