/**
 * File      : menu_sleep_callback.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "../menu/menu_sleep.h"
#include "menu_sleep_callback.h"
#include "../menu/configure.h"

void menu_sleep_register() {
    // menu_registerDrawCallback(&menuSleep, menuSleep_onDraw);
    // button_registerClickCallback(&buttonAwaken, buttonAwaken_onClick);
}

/**************************************
 * 事件响应
 *************************************/
// void menuSleep_onDraw(void *self) {
//     return;
// }

// void buttonAwaken_onClick(void *self) {
//     return;
// }

