/**
 * File      : menu_ae_callback.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "../menu/menu_ae.h"
#include "menu_ae_callback.h"
#include "../menu/configure.h"

void menu_ae_register() {
    // menu_registerDrawCallback(&menuAe, menuAe_onDraw);
    // scrollbar_registerDataChangeCallback(&scrollbarLuma, scrollbarLuma_onDataChange);
    // scrollbar_registerGetValueCallback(&scrollbarLuma, scrollbarLuma_onDraw);
    // combobox_registerDataChangeCallback(&comboboxAeMode, comboboxAeMode_onDataChange);
    // combobox_registerGetValueCallback(&comboboxAeMode, comboboxAeMode_onDraw);
    // scrollbar_registerDataChangeCallback(&scrollbarLv, scrollbarLv_onDataChange);
    // scrollbar_registerGetValueCallback(&scrollbarLv, scrollbarLv_onDraw);
    // combobox_registerDataChangeCallback(&comboboxAeGain, comboboxAeGain_onDataChange);
    // combobox_registerGetValueCallback(&comboboxAeGain, comboboxAeGain_onDraw);
    // button_registerClickCallback(&buttonAeMenuReturn, buttonAeMenuReturn_onClick);
}

/**************************************
 * 事件响应
 *************************************/
// void menuAe_onDraw(void *self) {
//     return;
// }

// void scrollbarLuma_onDataChange(void *self) {
//     return;
// }

// void scrollbarLuma_onDraw(void *self) {
//     return;
// }

// void comboboxAeMode_onDataChange(void *self) {
//     return;
// }

// void comboboxAeMode_onDraw(void *self) {
//     return;
// }

// void scrollbarLv_onDataChange(void *self) {
//     return;
// }

// void scrollbarLv_onDraw(void *self) {
//     return;
// }

// void comboboxAeGain_onDataChange(void *self) {
//     return;
// }

// void comboboxAeGain_onDraw(void *self) {
//     return;
// }

// void buttonAeMenuReturn_onClick(void *self) {
//     return;
// }

