/**
 * File      : menu_main_callback.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_MAIN_CALLBACK_H_
#define _MENU_MAIN_CALLBACK_H_


void menu_main_register();
// void menuMain_onDraw(void *self);
// void buttonAe_onClick(void *self);
// void buttonAwb_onClick(void *self);
// void buttonDayNight_onClick(void *self);
// void buttonImageEnhance_onClick(void *self);
// void buttonVideoOutput_onClick(void *self);
// void comboboxLanguage_onDataChange(void *self);
// void comboboxLanguage_onDraw(void *self);
// void buttonReset_onClick(void *self);
// void buttonSaveExit_onClick(void *self);
// void buttonExit_onClick(void *self);

#endif  // _MENU_MAIN_CALLBACK_H_
