/**
 * File      : menu_dayNight_callback.h
 * This file is automatically generated by menu_create.py
 * PLEASE DO NOT MODIFY THIS FILE DIRECTLY
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#ifndef _MENU_DAYNIGHT_CALLBACK_H_
#define _MENU_DAYNIGHT_CALLBACK_H_


void menu_dayNight_register();
// void menuDayNight_onDraw(void *self);
// void comboboxDayNightMode_onDataChange(void *self);
// void comboboxDayNightMode_onDraw(void *self);
// void comboboxInfraRed_onDataChange(void *self);
// void comboboxInfraRed_onDraw(void *self);
// void buttonDayNightReturn_onClick(void *self);

#endif  // _MENU_DAYNIGHT_CALLBACK_H_
