/**
 * File      : menu_imageEnhance_callback.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "../menu/menu_imageEnhance.h"
#include "menu_imageEnhance_callback.h"
#include "../menu/configure.h"

void menu_imageEnhance_register() {
    // menu_registerDrawCallback(&menuImageEnhance, menuImageEnhance_onDraw);
    // combobox_registerDataChangeCallback(&comboboxContrastMode, comboboxContrastMode_onDataChange);
    // combobox_registerGetValueCallback(&comboboxContrastMode, comboboxContrastMode_onDraw);
    // scrollbar_registerDataChangeCallback(&scrollbarContrast, scrollbarContrast_onDataChange);
    // scrollbar_registerGetValueCallback(&scrollbarContrast, scrollbarContrast_onDraw);
    // combobox_registerDataChangeCallback(&comboboxSharpnessMode, comboboxSharpnessMode_onDataChange);
    // combobox_registerGetValueCallback(&comboboxSharpnessMode, comboboxSharpnessMode_onDraw);
    // scrollbar_registerDataChangeCallback(&scrollbarSharpness, scrollbarSharpness_onDataChange);
    // scrollbar_registerGetValueCallback(&scrollbarSharpness, scrollbarSharpness_onDraw);
    // combobox_registerDataChangeCallback(&comboboxSaturateMode, comboboxSaturateMode_onDataChange);
    // combobox_registerGetValueCallback(&comboboxSaturateMode, comboboxSaturateMode_onDraw);
    // scrollbar_registerDataChangeCallback(&scrollbarSaturate, scrollbarSaturate_onDataChange);
    // scrollbar_registerGetValueCallback(&scrollbarSaturate, scrollbarSaturate_onDraw);
    // button_registerClickCallback(&buttonImageEnhanceReturn, buttonImageEnhanceReturn_onClick);
}

/**************************************
 * 事件响应
 *************************************/
// void menuImageEnhance_onDraw(void *self) {
//     return;
// }

// void comboboxContrastMode_onDataChange(void *self) {
//     return;
// }

// void comboboxContrastMode_onDraw(void *self) {
//     return;
// }

// void scrollbarContrast_onDataChange(void *self) {
//     return;
// }

// void scrollbarContrast_onDraw(void *self) {
//     return;
// }

// void comboboxSharpnessMode_onDataChange(void *self) {
//     return;
// }

// void comboboxSharpnessMode_onDraw(void *self) {
//     return;
// }

// void scrollbarSharpness_onDataChange(void *self) {
//     return;
// }

// void scrollbarSharpness_onDraw(void *self) {
//     return;
// }

// void comboboxSaturateMode_onDataChange(void *self) {
//     return;
// }

// void comboboxSaturateMode_onDraw(void *self) {
//     return;
// }

// void scrollbarSaturate_onDataChange(void *self) {
//     return;
// }

// void scrollbarSaturate_onDraw(void *self) {
//     return;
// }

// void buttonImageEnhanceReturn_onClick(void *self) {
//     return;
// }

