/**
 * File      : menu_dayNight_callback.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "../menu/menu_dayNight.h"
#include "menu_dayNight_callback.h"
#include "../menu/configure.h"

void menu_dayNight_register() {
    // menu_registerDrawCallback(&menuDayNight, menuDayNight_onDraw);
    // combobox_registerDataChangeCallback(&comboboxDayNightMode, comboboxDayNightMode_onDataChange);
    // combobox_registerGetValueCallback(&comboboxDayNightMode, comboboxDayNightMode_onDraw);
    // combobox_registerDataChangeCallback(&comboboxInfraRed, comboboxInfraRed_onDataChange);
    // combobox_registerGetValueCallback(&comboboxInfraRed, comboboxInfraRed_onDraw);
    // button_registerClickCallback(&buttonDayNightReturn, buttonDayNightReturn_onClick);
}

/**************************************
 * 事件响应
 *************************************/
// void menuDayNight_onDraw(void *self) {
//     return;
// }

// void comboboxDayNightMode_onDataChange(void *self) {
//     return;
// }

// void comboboxDayNightMode_onDraw(void *self) {
//     return;
// }

// void comboboxInfraRed_onDataChange(void *self) {
//     return;
// }

// void comboboxInfraRed_onDraw(void *self) {
//     return;
// }

// void buttonDayNightReturn_onClick(void *self) {
//     return;
// }

