/**
 * File      : menu_awb_callback.c
 * This file is automatically generated by menu_create.py
 * UNCOMMENT AND MODIFY CALLBACK FUNCTION AS REQUIRED
 *
 * Copyright (c) 2017 Shanghai Fullhan Microelectronics Co., Ltd.
 * All rights reserved
 *
 * Script Version: 3.0
 * Generated at: 2024-04-12 16:11:37
 */
#include "../menu/menu_awb.h"
#include "menu_awb_callback.h"
#include "../menu/configure.h"

void menu_awb_register() {
    // menu_registerDrawCallback(&menuAwb, menuAwb_onDraw);
    // combobox_registerDataChangeCallback(&comboboxAwbMode, comboboxAwbMode_onDataChange);
    // combobox_registerGetValueCallback(&comboboxAwbMode, comboboxAwbMode_onDraw);
    // scrollbar_registerDataChangeCallback(&scrollbarRgain, scrollbarRgain_onDataChange);
    // scrollbar_registerGetValueCallback(&scrollbarRgain, scrollbarRgain_onDraw);
    // scrollbar_registerDataChangeCallback(&scrollbarBgain, scrollbarBgain_onDataChange);
    // scrollbar_registerGetValueCallback(&scrollbarBgain, scrollbarBgain_onDraw);
    // button_registerClickCallback(&buttonAwbMenuReturn, buttonAwbMenuReturn_onClick);
}

/**************************************
 * 事件响应
 *************************************/
// void menuAwb_onDraw(void *self) {
//     return;
// }

// void comboboxAwbMode_onDataChange(void *self) {
//     return;
// }

// void comboboxAwbMode_onDraw(void *self) {
//     return;
// }

// void scrollbarRgain_onDataChange(void *self) {
//     return;
// }

// void scrollbarRgain_onDraw(void *self) {
//     return;
// }

// void scrollbarBgain_onDataChange(void *self) {
//     return;
// }

// void scrollbarBgain_onDraw(void *self) {
//     return;
// }

// void buttonAwbMenuReturn_onClick(void *self) {
//     return;
// }

